dpi_scale=auto
accent_color="#00bbff"
context_menu=yes
tooltip=yes
mouse_timeout=2
show_on_mouse_move=no
single_click_actions_enabled=yes
seeking_zone_percentage=15
seek_step_seconds=5
show_mini_seekbar=yes
window_controls=auto
youtube_quality=auto
# hwdec is configured in mpv.conf instead
force_hwdec=no
max_volume_percentage=150
directory_playlist=yes
directory_playlist_sort=name