color0 #171b24
color1 #ed8274
color2 #87d96c
color3 #facc6e
color4 #6dcbfa
color5 #dabafa
color6 #90e1c6
color7 #c7c7c7
color8 #686868
color9 #f28779
color10 #d5ff80
color11 #ffd173
color12 #73d0ff
color13 #dfbfff
color14 #95e6cb
color15 #ffffff

cursor                #ffcc66
cursor_text_color     #171c28
background            #171c28
foreground            #d1d1c7
selection_foreground  #1f2430
selection_background  #409fff
active_border_color   #e6b450
inactive_border_color #161a22
url_color             #e6b450

active_tab_foreground   #0b0e14
active_tab_background   #e6b450
inactive_tab_foreground #8e959e
inactive_tab_background #161a22
cursor_trail_color      #8e959e
