color0 #181210
color1 #ffb4ab
color2 #ffb59a
color3 #e7beaf
color4 #d5c68e
color5 #ffb59a
color6 #e7beaf
color7 #ede0dc
color8 #a08d86
color9 #ffb4ab
color10 #ffb59a
color11 #e7beaf
color12 #d5c68e
color13 #ffb59a
color14 #e7beaf
color15 #ede0dc

cursor                #ede0dc
cursor_text_color     #181210
background            #181210
foreground            #ede0dc
selection_foreground  #d8c2bb
selection_background  #53433e
active_border_color   #ffb59a
inactive_border_color #53433e
url_color             #ffb59a

active_tab_foreground   #5b1b00
active_tab_background   #ffb59a
inactive_tab_foreground #d8c2bb
inactive_tab_background #53433e
cursor_trail_color      #d8c2bb
