# Scroller Layout Setting
scroller_structs=20
scroller_default_proportion=0.5
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=0
scroller_ignore_proportion_single=0
scroller_default_proportion_single=0.98
scroller_proportion_preset=0.5,0.8,1.0

# Master-Stack Layout Setting
new_is_master=0
default_mfact=0.55
default_nmaster=1
smartgaps=0

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:*,layout_name:dwindle
# tagrule=id:1,layout_name:dwindle
# tagrule=id:2,layout_name:tile
# tagrule=id:3,layout_name:tile
# tagrule=id:4,layout_name:tile
# tagrule=id:5,layout_name:tile
