# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x121414ff
bordercolor = 0x8c9295ff
dropcolor = 0xaecbd880
splitcolor = 0xd5bfddff
focuscolor = 0xaecbd8ff
maximizescreencolor = 0xbdc8ceff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd5bfddff
globalcolor = 0x34505bff
overlaycolor = 0x404b4fff
jump_label_decorate_fg_color = 0xe3e2e3ff
jump_label_decorate_bg_color = 0x292a2bff
jump_label_decorate_focus_fg_color = 0x17343eff
jump_label_decorate_focus_bg_color = 0xaecbd8ff
jump_label_decorate_border_color = 0x8c9295ff
