# Window & UI
force-window=yes
border=no

# Hardware decoding — VAAPI works best for AMD GPUs (Radeon RX 460)
# Note: RX 460 does NOT support AV1 hardware decode (RDNA2+ required)
# hwdec=vaapi
vo=gpu-next
hwdec=auto-safe
hwdec-codecs=h264,hevc

# YouTube — prefer H.264/VP9 over AV1 (AV1 SW decode too heavy for this CPU)
# ytdl-format=bestvideo[height<=?1080]+bestaudio/best
#ytdl-format=bestvideo[vcodec!=av01][height<=?1080]+bestaudio/best
ytdl-format=bestvideo[vcodec^=avc1][height<=?1080]+bestaudio/bestvideo[vcodec!=av01][height<=?1080]+bestaudio/best
# ytdl-raw-options=format-sort=vcodec:h264:vp9:hevc:av01:res:br

# Audio
audio-exclusive=no
volume-max=150
audio-channels=auto
audio-normalize-downmix=yes
audio-spdif=ac3,dts,dts-hd,eac3,truehd
