stream.properties = {
    audio.format                = S24_32
    resample.quality            = 9
    channelmix.use-volume-sharing = false
}
pulse.properties = {
    pulse.min.req          = 256/48000
    pulse.min.quantum      = 256/48000
    pulse.max.quantum      = 4096/48000
}
