vim.cmd("highlight clear")

if vim.fn.exists("syntax_on") then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "custom"

vim.api.nvim_set_hl(0, "Normal", { fg = "#FEFEFE", bg = "NONE" }) -- or bg = '#202020'
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#FEFEFE", bg = "NONE" }) -- or bg = '#202020'
vim.api.nvim_set_hl(0, "Comment", { fg = "#6f7b68" })
vim.api.nvim_set_hl(0, "TSComment", { fg = "#6f7b68" })
vim.api.nvim_set_hl(0, "Conceal", { bg = "#262626" })
vim.api.nvim_set_hl(0, "Constant", { fg = "#cccccc" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#FFFEDB", bg = "#2B3328" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#FFFEDB", bg = "#262636" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#C34143", bg = "#42242B" })
vim.api.nvim_set_hl(0, "DiffText", { fg = "#FFFEDB", bg = "#49443C" })
vim.api.nvim_set_hl(0, "Directory", { fg = "#C1C88D" })
vim.api.nvim_set_hl(0, "Error", { fg = "#C34143", undercurl = true })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = "#FFFEDB" })
vim.api.nvim_set_hl(0, "Function", { fg = "#AA9AAC" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#8B9698" })
vim.api.nvim_set_hl(0, "LineNrAbove", { fg = "#888888", bg = "#222222" })
vim.api.nvim_set_hl(0, "LineNrBelow", { fg = "#888888", bg = "#222222" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#d6d2c8" })
vim.api.nvim_set_hl(0, "MatchParen", { fg = "#FFFEDB" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#303030" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#DEBF7C" })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#918988", bg = "#303030" })
vim.api.nvim_set_hl(0, "PmenuSbar", { fg = "#918988", bg = "#262626" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#BFBBBA", bg = "#303030" })
vim.api.nvim_set_hl(0, "PmenuThumb", { fg = "#918988", bg = "#262626", reverse = true })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#8B9698" })
vim.api.nvim_set_hl(0, "Question", { fg = "#9b8d7f" })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = "#303030" })
vim.api.nvim_set_hl(0, "Search", { bg = "#5F5958" })
vim.api.nvim_set_hl(0, "Special", { fg = "#cccccc" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#C1C88D" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#676767" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#cccccc" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#FFFEDB", bg = "#34383C" })
vim.api.nvim_set_hl(0, "String", { fg = "#A2A970" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#AA9AAC" })
vim.api.nvim_set_hl(0, "Substitute", { fg = "#1A1A1A", bg = "#C1C88D" })
vim.api.nvim_set_hl(0, "TabLine", { fg = "#A09998", bg = "#212121" })
vim.api.nvim_set_hl(0, "TabLineFill", { fg = "#A09998", bg = "#212121" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#A09998", bg = "#40474F" })
vim.api.nvim_set_hl(0, "Title", { fg = "#FFFEDB" })
vim.api.nvim_set_hl(0, "Todo", { fg = "#8B9698" })
vim.api.nvim_set_hl(0, "Type", { fg = "#E3D896" })
vim.api.nvim_set_hl(0, "Underlined", { undercurl = true })
vim.api.nvim_set_hl(0, "VertSplit", { fg = "#303030" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#454545" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#FFFEDB" })
vim.api.nvim_set_hl(0, "Float", { fg = "#6f7b68" })
vim.api.nvim_set_hl(0, "Number", { fg = "#6f7b68" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#6f7b68" })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = "#111111", fg = "#888888" })
vim.api.nvim_set_hl(0, "@markup.link.label.markdown_inline", {})
vim.api.nvim_set_hl(0, "LspInlayHint", {
	fg = "#6f7b68", -- text color
	bg = "NONE", -- transparent background (or use a color like "#262626")
	italic = true, -- optional: make it italic
})
