#!/usr/bin/env bash

SEARCH_DIRS=(
  "$HOME"
  "$HOME/Developer"
  "$HOME/repo"
  "$HOME/dot"
  "$HOME/.config"
)

if [[ $# -eq 1 ]]; then
  selected="$1"
else
  selected="$(
    fd -H -t d -d 2 -E '{.cache,.bun,.cargo}' --absolute-path . "${SEARCH_DIRS[@]}" |
      sed "s|^$HOME/||" |
      fzf --margin=2% --color --border --cycle --prompt="📁 search> " |
      sed "s|^|$HOME/|"
  )"
fi

[[ -z "$selected" ]] && exit 0

selected_name="$(basename "$selected" | tr ' ./:' '_')"

if [[ -z "${HERDR_ENV:-}" ]]; then
  exec herdr --session "$selected_name"
fi

workspace_id=$(herdr workspace list | jq -r ".workspaces[] | select(.label == \"$selected_name\") | .workspace_id" 2>/dev/null)

if [ -n "$workspace_id" ]; then
  herdr workspace focus "$workspace_id"
else
  herdr workspace create --cwd "$selected" --label "$selected_name" --focus >/dev/null
fi
