#!/bin/bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/$THEME"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar position="$BAR_POSITION" height="$BAR_HEIGHT" corner_radius="$BAR_CORNER_RADIUS" blur_radius="$BAR_BLUR_RADIUS" color="$BAR_COLOR" margin="$BAR_MARGIN" y_offset="$BAR_Y_OFFSET"

##### Changing Defaults #####
default=(
  # background.color="$BACKGROUND_COLOR"
  blur_radius=5
  background.corner_radius="$BACKGROUND_CORNER_RADIUS"
  background.height="$BACKGROUND_HEIGHT"
  icon.padding_left=12
  icon.padding_right=4
  label.padding_left="$LABEL_PADDING_LEFT"
  label.padding_right="$LABEL_PADDING_RIGHT"
  background.padding_left=18
  background.border_width="$BACKGROUND_BORDER_WIDTH"
  background.y_offset=2
  y_offset="$Y_OFFSET"
  icon.font="$ICON_FONT"
  label.font="$LABEL_FONT"
  icon.color="$LABEL_COLOR"
  label.color="$LABEL_COLOR"
  icon.drawing=on
  label.highlight_color="$LABEL_HIGHLIGHT_COLOR"
)
sketchybar --default "${default[@]}"

#-- Left items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

#---- right items -----------
source $ITEM_DIR/calender.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --hotload on
sketchybar --update
sketchybar --trigger rift_workspace_change RIFT_WORKSPACE_NAME="D"
