#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles
source "$CONFIG_DIR/colors.sh" # Loads all defined colors
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=25 corner_radius=20 blur_radius=10 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  background.color=$BG
  blur_radius=2
  background.corner_radius=15
  background.height=30
  icon.padding_left=12
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=12
  background.padding_left=18
  background.border_width=1
  background.y_offset=2
  y_offset=3
  icon.font="SF Pro:bold:15.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color=$LABEL_COLOR
  label.color=$WHITE

)
sketchybar --default "${default[@]}"
#-- Left items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh
#---- right items -----------
source $ITEM_DIR/calender.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --hotload on
sketchybar --update
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
