require("core.lazy")
require("core.lsp")
require("core.Mason-path")
require("config.mason-verify")
require("config.keymaps")
require("config.opts")
require("config.autocmds")
require("config.statusline")
vim.cmd(":hi statusline guibg=NONE")
