require("core.lazy")
require("config.utils")
-- require("custom.colorscheme")
require("core.lsp")
require("core.Mason-path")
require("config.mason-verify")
require("config.keymaps")
require("config.opts")
require("config.autocmds")
require("config.statusline")
require("custom.startup")
vim.cmd(":hi statusline guibg=NONE")
